travis:
  secure:
    BINSTAR_TOKEN: fYlNaqQMBE0fGCXONvbRJOv4Vq1F2VW75Ja2r4z/E+0kRnGamwEenA58rQNRh9gyMiQYf55Uqz6SkS12bix8p7B1gx+q0PwYPXLWRPN0FOq9q06j+fZoENLywoDsMi+9VjpvAGiI98YUXLT2WW0hNFmOB9t8jnyyBgwFSKtLtBOeotjC/nNVE9AqCIIitcCI0bXnJm0R2Jb6gnDlc87MNOKaQNWHOpKv8wRhGUF/qp1eckjIdFFq0bflPe4j712Z0Cvm0be1O/ZN4oEqMFSjGjmU8D+UVGkwiDLgZgyGGeJOp7/uYDIZ1HfpdwmHCmPisaSOLMfWPuefwOnk4MvasK4ht16POfKNv0C5rzcc1Fyq+5W0VnR03q9CPouWzjyGLJTUnOj5HaLEDXWURiaug1k5Nzm0XdY4Dk1B3fD8nAFdv5k97eWsixWg2podneeUGG6kOQdrIf5bjPkwQ7L/L3RdXZESeeOhTpnt4baDJPJ4QT6frAyxIYiTnY/QqUKc0gmXforI89AerGJvxgibs/far2c/9LitZ45brbG3/AgbY4wqes2C1uvcDJzqDlF8tdFzGSg4hsryVedHm4xHGaK/BPawKqeZNXEdI2aiFwJKTzCCWz1p0EynGgTpNpc9IqpdLTWE2wZUcuIUfNbySIt13O89+0X3ZNdeg6pje1E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
